modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/rathmerdominik/devilfruit-circulation-bot/issues/"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	updateJSONURL="https://raw.githubusercontent.com/rathmerdominik/devilfruit-circulation-bot/main/updates.json"
	displayURL="https://github.com/rathmerdominik/devilfruit-circulation-bot"
	logoFile="dfcirc.png"
	credits="DerHammerclock\nDrqonic for his insane help <3"
	authors="${mod_authors}"
	description='''${mod_description}'''

[[dependencies.mineminenomi]] 
	modId = "mineminenomi"
	mandatory = true
	versionRange = "[0.9.5,)"
	ordering = "AFTER"
	side = "SERVER"

[[dependencies.dcintegration]]
	modId="dcintegration"
	mandatory=true
	versionRange="[3.0.5,)"
	ordering="AFTER"
	side="SERVER"